### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by XGhozt00** [alexstandiford/easy-age-verifier#76] opened 2017-01-28 01:32 UTC
I've tried this on two different WP installations and it simply doesn't show up at all. It used to work fine and stopped working with the last update that now uses the Customizer. Am I missing something?

**Comment by alexstandiford** [comment] 2017-01-28 01:36
Did you do any customizations to the plugin, or did you just use it as-is?

Can you open each website in an incognito window, and tell me if you see any javacript errors?

Can you check to see if "verifier.js" loaded when you load the page?

**Comment by wademckelvey** [comment] 2017-01-29 17:26
Having the same issue.  Installed through WP plugins, and can't get it to show through Incognito mode or any other way.  I'm not seeing verifier.js show up in my sources.

**Comment by alexstandiford** [comment] 2017-01-29 19:44
Ok. When you edit the form in the customizer, visit it and save the customizer. I think this is related to the database upgrade. Let me know if that resolves it

**Comment by alexstandiford** [comment] 2017-02-01 11:34
I've researched this issue a little closer. It appears the issue is caused by the choice of hook I used to call the verifier. On some themes, this call was too late. I'm pushing an update to this now!

**Comment by alexstandiford** [comment] 2017-02-01 11:43
If either of you are still using the verifier, please update and let me know if it solves the problem.

If you're in a hurry, and know what you're doing, feel free to duplicate what I did to this file, here:
https://github.com/alexstandiford/easy-age-verifier/commit/340c9c8a85dd47e2618a5aa04cd694d2800eb0c7

The critical part is lines 102-103.

**Comment by XGhozt00** [comment] 2017-02-01 20:13
Thank you! I will give it a shot asap

**Comment by alexstandiford** [comment] 2017-02-03 11:30
Awesome - let me know how it goes.

**Comment by XGhozt00** [comment] 2017-02-08 23:04
From what I can tell, it's still not working on Version 2.02

**Comment by alexstandiford** [comment] 2017-02-09 10:46
Do you run a caching I've built the plugin to avoid caching issues, but sometimes it gets caught up in a cache, especially in situations where the plugin went through a significant update.

**Comment by XGhozt00** [comment] 2017-02-10 02:37
I tried it on two different sites again and it just doesn't do anything. :(
I install the old version, and then it works fine.

**Comment by alexstandiford** [comment] 2017-02-10 15:28
I _suspect_ that this may be a result of the AJAX call not going through successfully. Can you try following these steps to see if it resolves the issue?

## First test:

* In your theme directory, create a new folder called `eav`.
* Browse to `wp-content/plugins/easy-age-verifier/lib/assets/templates/` and copy `default.php`
* Paste `default.php` into your newly created `eav` directory.

## Test your verifier. If it still doesn't work, follow these steps:

* If you followed the previous steps above, remove the `eav` directory you added.
* Open your theme’s `functions.php` file.
* Copy and paste [this text](https://gist.github.com/alexstandiford/e678be1d328f51205fc6e9d00f6d5348) in your functions.php file

One of those two should fix the problem. _Please_ let me know which one resolved your issue as this will help me confirm my suspected issue.

**Comment by alexstandiford** [comment] 2017-02-19 16:17
Hey @XGhozt00 - Did you find time to test this out? I'm rolling out an update to this plugin that will fix the issue based on what I suspect the cause of the problem to be, but figured I'd check-in to see if you got this solved.

**Comment by alexstandiford** [comment] 2017-02-22 01:13
Marking as closed. Feel free to re-open when/if you ever come back!

**Closed by alexstandiford** 2017-02-22 01:13 UTC
